### PR TITLE
feat: support supplying SSH credentials via command line args

### PR DESCRIPTION
**Pull request by jaredhagen**
## Pull Request 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other: (describe here) 
  
## Proposed Change
Issue Number: #21

This change adds the ability to specify SSH credentials via command line arguments within the Gitlab Runner `config.toml`.  This method of setting these credentials prevents exposing the credentials via environment variables within the job being run.  Values provided via environment variables will override values provided via command line arguments.

## Breaking Change?

- [ ] Yes
- [x] No

## Checklist

Please validate that your PR fulfills the following requirements:
- [x] I have read the **CONTRIBUTING.md** documentation (if available)
- [x] I have branched from the default repo branch (can be master, main, or release/vX.X)
- [x] I have checked that a similar PR does not exist or has been rejected in the past
- [x] PR changes are specific to a feature or bug
- [x] No style/format/cosmetic changes included
- [x] I have used existing style and naming patterns in my changes
- [ ] Tests for the changes have been added/updated (if relevant)
- [x] Built/compiled and tested locally
- [x] Docs have been added/updated (if relevant)
- [x] I have squashed my changes into a single commit

### CODE REVIEW

**Comment by github-service-user-veertu** [comment]
Can one of the admins verify this patch?

**Comment by NorseGaud** [comment]
ok to test

**Comment by NorseGaud** [comment]
@github-service-user-veertu run tests

**Comment by NorseGaud** [comment]
run tests

**Comment by NorseGaud** [comment]
@github-service-user-veertu run tests

**Pull request merged**
